#import <Foundation/Foundation.h>
#import "LGInlineResponse200.h"
#import "LGApi.h"

/**
* Logly lift.json API
* Logly lift.json API for Lift Mobile SDK
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface LGDefaultApi: NSObject <LGApi>

extern NSString* kLGDefaultApiErrorDomain;
extern NSInteger kLGDefaultApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Liftレコメンデーション結果検索
/// Liftレコメンデーション結果検索 注：返される結果数はLogly Lift コンソールの方で設定するが、表示はエリアの空きがある分だけ表示される
///
/// @param adspotId Lift adspot ID
/// @param widgetId Lift wiget ID
/// @param url キーとなるページ URL (MDL)
/// @param ref リファラーURL（通常Mobileでは必要なし） (optional)
/// @param toplevel json toplevel hash名: 通常は&#39;items&#39;を指定 (optional) (default to items)
/// 
///  code:200 message:"正常実行時"
///
/// @return LGInlineResponse200*
-(NSNumber*) requestLiftWithAdspotId: (NSNumber*) adspotId
    widgetId: (NSNumber*) widgetId
    url: (NSString*) url
    ref: (NSString*) ref
    toplevel: (NSString*) toplevel
    completionHandler: (void (^)(LGInlineResponse200* output, NSError* error)) handler;



@end
