#import <Foundation/Foundation.h>
#import "LGInlineResponse200.h"
#import "LGApi.h"

/**
* Logly lift.json API
* Logly lift.json API for Lift Mobile SDK
*
* OpenAPI spec version: 1.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface LGDefaultApi: NSObject <LGApi>

extern NSString* kLGDefaultApiErrorDomain;
extern NSInteger kLGDefaultApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(LGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Liftレコメンデーション結果検索
/// Liftレコメンデーション結果検索 注：返される結果数はLogly Lift コンソールの方で設定するが、表示はエリアの空きがある分だけ表示される
///
/// @param adspotId Lift adspot ID
/// @param widgetId Lift wiget ID
/// @param url キーとなるページ URL (MDL)
/// @param ref リファラーURL（通常Mobileでは必要なし） (optional)
/// @param toplevel jsonトップレベルhash名: 通常は&#39;items&#39;を指定 (optional) (default to items)
/// 
///  code:200 message:"正常実行時"
///
/// @return LGInlineResponse200*
-(NSURLSessionTask*) requestLiftWithAdspotId: (NSNumber*) adspotId
    widgetId: (NSNumber*) widgetId
    url: (NSString*) url
    ref: (NSString*) ref
    toplevel: (NSString*) toplevel
    completionHandler: (void (^)(LGInlineResponse200* output, NSError* error)) handler;



@end
