#import <Foundation/Foundation.h>
#import <JSONModel/JSONValueTransformer.h>

/**
* Logly lift.json API
* Logly lift.json API for Lift Mobile SDK
*
* OpenAPI spec version: 1.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface JSONValueTransformer (ISO8601)

@end
