#import <Foundation/Foundation.h>
#import "LGObject.h"

/**
* Logly lift.json API
* Logly lift.json API for Lift Mobile SDK
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol LGInlineResponse200Items
@end

@interface LGInlineResponse200Items : LGObject

/* 出版日 [optional]
 */
@property(nonatomic) NSString* publishedAt;
/* リード（サマリー） [optional]
 */
@property(nonatomic) NSString* lead;
/* レコメンドが見つからず、広告が帰ってきた場合のtitle [optional]
 */
@property(nonatomic) NSString* advertisingSubject;
/* スコア（内部使用変数） [optional]
 */
@property(nonatomic) NSNumber* score;
/* イメージの幅pixel [optional]
 */
@property(nonatomic) NSNumber* imageWidth;
/* 計測用ビーコンURL(表示した時にアクセスしてください） [optional]
 */
@property(nonatomic) NSString* beaconUrl;
/* イメージの高さpixel [optional]
 */
@property(nonatomic) NSNumber* imageHeight;

@property(nonatomic) NSString* site;
/* 1 = true, レコメンドが見つからず、広告が返ってきた場合 [optional]
 */
@property(nonatomic) NSNumber* isArticle;
/* イメージのURL [optional]
 */
@property(nonatomic) NSString* imageUrl;
/* click計測用のアクセスURL(アクセスするとld_urlと同じURLへのリダイレクトが返信される) [optional]
 */
@property(nonatomic) NSString* url;
/* タイトル [optional]
 */
@property(nonatomic) NSString* title;
/* ページのURL(MDL) [optional]
 */
@property(nonatomic) NSString* ldUrl;

@end
