#import <Foundation/Foundation.h>
#import "LGObject.h"

/**
* Logly lift.json API
* Logly lift.json API for Lift Mobile SDK
*
* OpenAPI spec version: 1.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "LGInlineResponse200Items.h"


@protocol LGInlineResponse200
@end

@interface LGInlineResponse200 : LGObject


@property(nonatomic) NSArray<LGInlineResponse200Items>* items;

@end
